spring:
  application:
    name: petshop-auth-api
  web:
    resources:
      add-mappings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      enabled-by-default: true

server:
  port: 5004
  servlet:
    context-path: /petshop-auth-api
    encoding:
      charset: UTF-8
      enabled: true
  max-http-request-header-size: 48000
  error:
    include-stacktrace: never

encryption:
  aes:
    key: ${ENCRYPTION_AES_KEY} # p&tsh0p-s7st3m
    algorithmic: AES/CBC/PKCS5PADDING

jwt:
  app:
    jwt-secret: ${JWT_SECRET}
    jwt-expiration-ms: 1800 # 30 minutos

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/petshop-system
    username: petshop-system
    password: test1234
    driverClassName: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
  sql:
    init:
      mode: always
      platform: postgres

redis:
  host: localhost
  port: 6379
  database: 3

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/petshop-system
    username: petshop-system
    password: test1234
    driverClassName: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
  sql:
    init:
      mode: always
      platform: postgres

redis:
  host: redis
  port: 6379
  database: 3
